import { Resend } from "resend"

const resend = new Resend(Bun.env.resend_token);


const generateHtmlTemplate = (dateString: string) => `
<div style="font-family: sans-serif; padding: 20px; color: #333; max-width: 600px; margin: 0 auto; border: 1px solid #eee; border-radius: 8px;">
    <h2 style="color: #d9534f; margin-top: 0;">Homelab System Notification</h2>
    <p>An interruption has been detected in the regular communication signal from your local server instance.</p>
    
    <table style="width: 100%; margin: 20px 0; border-collapse: collapse;">
        <tr>
            <td style="padding: 8px; border-bottom: 1px solid #ddd; font-weight: bold;">Event Status:</td>
            <td style="padding: 8px; border-bottom: 1px solid #ddd; color: #d9534f;">Missed Heartbeat (Offline)</td>
        </tr>
        <tr>
            <td style="padding: 8px; border-bottom: 1px solid #ddd; font-weight: bold;">Timestamp:</td>
            <td style="padding: 8px; border-bottom: 1px solid #ddd;">${dateString}</td>
        </tr>
    </table>

    <p style="font-size: 14px; color: #666;">Please verify the network connectivity of your local machine or check the status of your running container services.</p>
    <hr style="border: 0; border-top: 1px solid #eee; margin: 20px 0;">
    <p style="font-size: 12px; color: #999; text-align: center;">This is an automated operational alert generated by the monitoring system at nxbim.xyz.</p>
</div>
`

export const AlertEmail = async () => {
    const email = Bun.env.email
    if (!email) return;
    const currentDateTime = new Date().toUTCString();
    try {
        const { data, error } = await resend.emails.send({
            from: "AlertEmail <support@nxbin.xyz>",
            to: email,
            subject: "Alert Homelab Down",
            html: generateHtmlTemplate(currentDateTime),
        });
        if (error) {
            console.log("resend reject", JSON.stringify(error, null, 2));
            return
        }
        console.log("send email", data?.id)
    } catch (err) {
        console.log("Exception", err)
    }
}
